## Analysis

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(data.table)
library(lmtest)
library(sandwich)
library(stargazer)
library(dplyr)
``` 

```{r Check if dataset exists}
tryCatch(
  {
    nrow(dataset)
  },
  error = function(e) {
    print("dataset variable not found, cannot proceed further!")
    stop(e)
  }
)
```
```{r}
# load Q1 data - WM vs BM
Q1 = dataset[QNum == 1 & IsAttrited == FALSE & IsNeverTaker == FALSE, ]
```

```{r}

# Lets perform the difference in differences manually for Q1 and then verify it with a regression model
A = mean(Q1[TreatmentAssignment == TRUE, ResponseQ])
B = mean(Q1[TreatmentAssignment == FALSE, ResponseQ])
```

```{r}
mod_q1 = lm(ResponseQ ~ TreatmentAssignment, data = Q1)
summary(mod_q1)
```

>From the above, we notice that the treatment coefficient value from the regression ```r mod_q1$coefficients[2]``` exactly matches what we obtained from our manual differences in differences model. `A - B =` ```r A-B```. There seems to be a favorable significant effect for white males since the DiD result is negative.

>Next, we attempt to add covariates into the analysis